### ISSUE TITLE
How to get valid Cairo2 json file

### ISSUE THREAD

**Issue by chan-bing** [FuzzingLabs/thoth#141]
Hi, i do not know how to get the valid json file. Currently, I can only get json files that start with "{"sierra_program":["0x1","0x3","0x0","0x2","0x2","0x0","0x109","0xf7","0x23","0x52616e6765436865636b","0x800000000000000100000000000000000000000000000000",.......". And my version of Cairo is 2.2.0, thank you!

**Comment by Rog3rSm1th** [comment]
This issue is normally resolved by thoth 0.11.0, and it is now possible to convert these files to Sierra using the converter available [here](https://github.com/FuzzingLabs/thoth/tree/master/contract-class-converter). You can then analyze them with [thoth-sierra](https://github.com/FuzzingLabs/thoth/tree/master/sierra).

**Comment by Rog3rSm1th** [comment]
Hello, for now thoth-sierra only allows you to decompile a sierra program without taking the ABI as a parameter.

**Comment by nikoulai** [comment]
Can I help with this? Could you provide a rough description of what should be done, please?
